spring:
  application:
    name: config-client

server:
  port: 8091

eureka:
  server: #官方不存在的配置（自定义配置）
    host: 127.0.0.1
    port: 8081
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:8081/eureka
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
