# eureka所有注册的服务: http://localhost:8081/eureka/apps
# eureka所有注册的指定服务: http://${host}:${port}/eureka/apps/${app_name}
# eureka所有注册的指定服务: http://${host}:${port}/eureka/apps/${app_name}/${app_instance_id}
server:
  port: 8081

spring:
  application:
    name: eureka-server

eureka:
  client:
     # 不向注册中心注册自己
    register-with-eureka: false
     # 不检索服务
    fetch-registry: false




